-- Add sha256 column to files table
ALTER TABLE files ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64) DEFAULT 'not_calculated_yet';

-- Update existing records to have the default value (though column default handles it)
UPDATE files SET sha256 = 'not_calculated_yet' WHERE sha256 IS NULL;

ALTER TABLE buckets ADD COLUMN IF NOT EXISTS storage_host_id VARCHAR(64) DEFAULT '';

CREATE TABLE IF NOT EXISTS hosts (
    id VARCHAR(255) PRIMARY KEY
);

ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ssh_user TEXT;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS available_templates TEXT[] DEFAULT '{}';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ssh_private_key TEXT;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS cpu_total DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS cpu_used DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ram_total DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ram_free DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS disk_total DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS disk_free DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS hosttype TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS hostname TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ip TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS status TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS last_heartbeat TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();




CREATE TABLE vm_metrics (
    id            BIGSERIAL PRIMARY KEY,
    vm_id         TEXT NOT NULL,
    host_id       TEXT NOT NULL,
    name          VARCHAR(255) NOT NULL,
    state         VARCHAR(50) NOT NULL,
    cpu_used      DOUBLE PRECISION NOT NULL DEFAULT 0,
    memory_used   BIGINT NOT NULL DEFAULT 0,
    disk_read     BIGINT NOT NULL DEFAULT 0,
    disk_write    BIGINT NOT NULL DEFAULT 0,
    net_rx        BIGINT NOT NULL DEFAULT 0,
    net_tx        BIGINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Useful for time-series queries per VM
CREATE INDEX idx_vm_metrics_vm_id_created_at ON vm_metrics (vm_id, created_at DESC);
CREATE INDEX idx_vm_metrics_host_id ON vm_metrics (host_id);





ALTER TABLE files ADD COLUMN IF NOT EXISTS folder_id VARCHAR(255) NOT NULL DEFAULT '';
 ALTER TABLE files ADD COLUMN IF NOT EXISTS file_name VARCHAR(255) NOT NULL DEFAULT '';
