-- Add sha256 column to files table
ALTER TABLE files ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64) DEFAULT 'not_calculated_yet';

-- Update existing records to have the default value (though column default handles it)
UPDATE files SET sha256 = 'not_calculated_yet' WHERE sha256 IS NULL;

ALTER TABLE buckets ADD COLUMN IF NOT EXISTS storage_host_id VARCHAR(64) DEFAULT '';

CREATE TABLE IF NOT EXISTS hosts (
    id VARCHAR(255) PRIMARY KEY
);

ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ssh_user TEXT;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS available_templates TEXT[] DEFAULT '{}';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ssh_private_key TEXT;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS cpu_total DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS cpu_used DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ram_total DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ram_free DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS disk_total DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS disk_free DOUBLE PRECISION;
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS hosttype TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS hostname TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS ip TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS status TEXT DEFAULT '';
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS last_heartbeat TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE hosts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();