name: CI - Run Tests

on:
  push:
    branches: [ "main", "dev", "featu/**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'

    - name: Run Tests
      run: go test ./... -v
