name: Prod Deployment

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            qarani/s3-server:prod-${{github.sha}}
            qarani/s3-server:prod

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          script: |
            docker network create aws-prod-network || true
            docker pull qarani/s3-server:prod-${{github.sha}}
            docker stop s3-server-prod || true
            docker rm s3-server-prod || true
            docker run -d \
              --name s3-server-prod \
              --network aws-prod-network \
              -p 8082:8099 \
              -e APP_PROFILE=prod \
              -e SERVER_PORT=8099 \
              -e POSTGRES_HOST=postgres-prod \
              -e POSTGRES_PORT=5432 \
              -e POSTGRES_USER=postgres-prod-user \
              -e POSTGRES_PASSWORD=postgres-prod-password \
              -e POSTGRES_DB=s3_db \
              -e POSTGRES_SSL_MODE=disable \
              -e EUREKA_HOSTNAME=s3-server-prod \
              -e EUREKA_IP_ADDR=127.0.0.1 \
              -e EUREKA_SERVER_URL=http://discovery-server-prod:8761/eureka \
              -e EUREKA_APP_NAME=S3-SERVICE \
              -e EUREKA_VIP_ADDRESS=s3-service \
              -e EUREKA_INSTANCE_ID=s3-service-prod:8099 \
              -e NATS_URL=nats://nats-prod:4222 \
              -e NATS_USER=nats-prod-user \
              -e NATS_PASSWORD=nats-prod-password \
              -e MINIO_ENDPOINT=minio-prod:9000 \
              -e MINIO_ACCESS_KEY=minio-prod-user \
              -e MINIO_SECRET_KEY=minio-prod-password \
              -e MINIO_USE_SSL=false \
              -e NATS_PREFIX=prod.v1 \
              qarani/s3-server:prod-${{github.sha}}




